### ISSUE TITLE
BUG: only supports png base64 strings

### ISSUE THREAD

**Issue by renarsvilnis** [miguelmota/is-base64#1]
Current `isBase64` regex only detects `png` files.

**Edit:** Made a pull request #2 that adds detection for any mimetype

**Comment by miguelmota** [comment]
@renarsvilnis great work, thanks!

**Comment by renarsvilnis** [comment]
@miguelmota No problem and don't forget to bump and push updates to npm.

`npm version patch && npm publish && git push --tags`

better yet as it is currently version 0.0.1 make it 1.0.0 by using `npm version major` instead of `npm version patch`

👍
