### ISSUE TITLE
Any string of 4 characters, consisting of letters and numbers, can pass the check.

### ISSUE THREAD

**Issue by derrick-null** [miguelmota/is-base64#13]
Any string of 4 characters, consisting of letters and numbers, can pass the check.

`
console.log(isBase64('X209')); // true
console.log(isBase64('1234')); // true
console.log(isBase64('AABB')); // true
console.log(isBase64('AV12')); // true
console.log(isBase64('123A')); // true
`

**Comment by miguelmota** [comment]
@derrick-null are some of those strings not valid base64 characters?

![Screenshot from 2020-10-20 20-44-22](https://user-images.githubusercontent.com/168240/96670793-1a373a00-1315-11eb-889b-b39c7fac8ee3.png)


https://en.wikipedia.org/wiki/Base64
