### ISSUE TITLE
Corner case

### ISSUE THREAD

**Issue by dy** [miguelmota/is-base64#3]
Hi @miguelmota!
Just stumbled upon
```js
isBase64('uuLMhh') //false
```
Although that ↑ should be `true`

**Comment by miguelmota** [comment]
@dfcreative the reason is because padding is required for it to be a valid *padded* base64 string 
 (length multiple of four)

```js
console.log(isBase64('uuLMhh==')); // true
```

However I just added an options object if you'd like to check without padding

```js
console.log(isBase64('uuLMhh')); // false
console.log(isBase64('uuLMhh', {paddingRequired: false})); // true
```

Thanks for reporting!
