### ISSUE TITLE
Option to detect if string is base64 without mime

### ISSUE THREAD

**Issue by dy** [miguelmota/is-base64#5]
Hi @miguelmota!

Sometimes there are cases when we can easily handle datauri strings

```js
var img = new Image(); img.src = dataUriString
```

but we cannot that easily handle raw base64 string, we have to convert them to datauri via [create-data-uri](https://ghub.io/create-data-uri) or alike.

That would be nice to have an option to detect only base64 string without mime type:

```js
isBase64('data:image/png;base64,iVBORw0KGgoAAAA ... AAElFTkSuQmCC') // true
isBase64('data:image/png;base64,iVBORw0KGgoAAAA ... AAElFTkSuQmCC', {mime: false}) // false
```

**Comment by miguelmota** [comment]
Hey @dy, great suggestion

the latest release has the `mime` option now

```js
console.log(isBase64('data:image/png;base64,iVBORw0KGgoAAAA ... AAElFTkSuQmCC', {mime: true})) // true
console.log(isBase64('data:image/png;base64,iVBORw0KGgoAAAA ... AAElFTkSuQmCC', {mime: false})) // false
console.log(isBase64('data:image/png;base64,iVBORw0KGgoAAAA ... AAElFTkSuQmCC')) // false
```

the mime flag is required now for returning true for valid base64 strings prefixed with the mime
