### ISSUE TITLE
isBase64('admin111') === true

### ISSUE THREAD

**Issue by zctya** [miguelmota/is-base64#8]
isBase64('admin111') === true

**Comment by miguelmota** [comment]
`admin111` is a valid base64 string

<a href="https://en.wikipedia.org/wiki/Base64"><img width="686" alt="Screen Shot 2019-08-31 at 11 36 40 AM" src="https://user-images.githubusercontent.com/168240/64067814-a05d6200-cbe3-11e9-9203-281801745eda.png"></a>

Closing issue. Create a new issue if you think it's still a problem.
