### ISSUE TITLE
Doesn't work on string "test"

### ISSUE THREAD

**Issue by idleberg** [miguelmota/is-base64#9]
I've noticed that testing the string "test" will report true:

```js
isBase64('test');
// => true
```

The same is true for other combinations of the same letters, such as "estt", "sett" etc.

**Comment by miguelmota** [comment]
@idleberg the letters in "test" are valid base64 characters. Can you explain why it should not be valid?

```node
const s = 'test'
console.log(Buffer.from(s, 'base64').toString('base64') === s) // true
```


<a href="https://en.wikipedia.org/wiki/Base64"><img width="686" alt="Screen Shot 2019-08-31 at 11 36 40 AM" src="https://user-images.githubusercontent.com/168240/64067814-a05d6200-cbe3-11e9-9203-281801745eda.png"></a>

**Comment by idleberg** [comment]
Thanks for the clarification, that explains why all other implementations produced the same result. This also means that there is no way to tell apart certain Base64-encoded strings from plain-text – I was hoping this was possible. Too bad!

**Comment by miguelmota** [comment]
@idleberg I'd guess you'd have to check the encoding of the decoded base64 string to check if matches the encoding you're expecting but yeah it's not really possible to tell an ascii string apart from a base64 string since they're the same characters
